# Generated by Django 2.2.8 on 2023-11-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
